version: 2.1

orbs:
  docker: circleci/docker@1.1.0

jobs:
  build-and-publish:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t my-dockerhub-username/my-docker-image-name .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push my-dockerhub-username/my-docker-image-name

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-publish:
          context: dockerhub
